### PR TITLE
Added TicTacToe game project

### PR DESCRIPTION
**Pull request by Muazzy**
Added a Tictactoe game project, which is made with some basic stuff like loops and conditional statements etc

### CODE REVIEW

**Review by Frahma07 — COMMENTED** [review]
Your code was pretty good. I think you can add a statement to choose the number because when I choose a letter there will be looping.

**Comment by Muazzy** [comment]
Thanks, sure ill take it into consideration.

**Comment by Muazzy** [comment]
also, would you add the hacktoberfest-accepted label on my PR, it'll help too much, Thanks

**Comment by Frahma07** [comment]
I already merged your pull request. If you want to add hacktoberfest-accepted label on your project, you need to go to the setting in your project and add the label by yourself.

**Comment by Muazzy** [comment]
sorry but only a maintainer of the repo can add the labels

**Comment by Muazzy** [comment]
so i cant add labels to my own PR, I am making another PR in this repo so please add the hacktoberfest-accepted label on it?

**Comment by Frahma07** [comment]
I already merged your PR. Please check your hacktoberfest profile.

**Comment by Muazzy** [comment]
yeah thanks but the rules have changed only PRs with the label hacktoberfest-accepted will be counted until and unless the repos name is "Hacktoberfest". so I made another PR in your repo please merge it and add the label, hope you understand, thanks. :)

**Comment by Frahma07** [comment]
I think you can add topics hacktoberfest-accepted in setting by yourself because I can't find the labels.

**Comment by Muazzy** [comment]
no i cant, its okay if you cant find the labels :(

**Comment by Frahma07** [comment]
Sorry, I can't find the labels

**Pull request merged**
